In [1]:
import findspark
findspark.init('/home/ubuntu/spark-2.4.5-bin-hadoop2.7')
from pyspark.sql import SparkSession
from pyspark.sql.types import (StructField, IntegerType,
                              StringType, StructType)
from pyspark.sql.functions import (dayofmonth, hour, dayofyear, month, year,
                                  weekofyear, format_number, date_format)
import os
os.chdir('/home/ubuntu/data')

In [2]:
spark = SparkSession.builder.appName('ops').getOrCreate()

In [3]:
df = spark.read.csv('appl_stock.csv', inferSchema=True, header=True)

In [4]:
df.printSchema()

root
 |-- Date: timestamp (nullable = true)
 |-- Open: double (nullable = true)
 |-- High: double (nullable = true)
 |-- Low: double (nullable = true)
 |-- Close: double (nullable = true)
 |-- Volume: integer (nullable = true)
 |-- Adj Close: double (nullable = true)

In [5]:
df.show()

+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
|               Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
|2010-01-04 00:00:00|        213.429998|        214.499996|212.38000099999996|        214.009998|123432400|         27.727039|
|2010-01-05 00:00:00|        214.599998|        215.589994|        213.249994|        214.379993|150476200|27.774976000000002|
|2010-01-06 00:00:00|        214.379993|            215.23|        210.750004|        210.969995|138040000|27.333178000000004|
|2010-01-07 00:00:00|            211.75|        212.000006|        209.050005|            210.58|119282800|          27.28265|
|2010-01-08 00:00:00|        210.299994|        212.000006|209.06000500000002|211.98000499999998|111902700|         27.464034|
|2010-01-11 00:00:00|212.79999700000002|        213.000002|        208.450005|210.11000299999998|115557400|         27.221758|
|2010-01-12 00:00:00|209.18999499999998|209.76999500000002|        206.419998|        207.720001|148614900|          26.91211|
|2010-01-13 00:00:00|        207.870005|210.92999500000002|        204.099998|        210.650002|151473000|          27.29172|
|2010-01-14 00:00:00|210.11000299999998|210.45999700000002|        209.020004|            209.43|108223500|         27.133657|
|2010-01-15 00:00:00|210.92999500000002|211.59999700000003|        205.869999|            205.93|148516900|26.680197999999997|
|2010-01-19 00:00:00|        208.330002|215.18999900000003|        207.240004|        215.039995|182501900|27.860484999999997|
|2010-01-20 00:00:00|        214.910006|        215.549994|        209.500002|            211.73|153038200|         27.431644|
|2010-01-21 00:00:00|        212.079994|213.30999599999998|        207.210003|        208.069996|152038600|         26.957455|
|2010-01-22 00:00:00|206.78000600000001|        207.499996|            197.16|            197.75|220441900|         25.620401|
|2010-01-25 00:00:00|202.51000200000001|        204.699999|        200.190002|        203.070002|266424900|26.309658000000002|
|2010-01-26 00:00:00|205.95000100000001|        213.710005|        202.580004|        205.940001|466777500|         26.681494|
|2010-01-27 00:00:00|        206.849995|            210.58|        199.530001|        207.880005|430642100|26.932840000000002|
|2010-01-28 00:00:00|        204.930004|        205.500004|        198.699995|        199.289995|293375600|25.819922000000002|
|2010-01-29 00:00:00|        201.079996|        202.199995|        190.250002|        192.060003|311488100|         24.883208|
|2010-02-01 00:00:00|192.36999699999998|             196.0|191.29999899999999|        194.729998|187469100|         25.229131|
+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [6]:
df.head(3)[0]

Row(Date=datetime.datetime(2010, 1, 4, 0, 0), Open=213.429998, High=214.499996, Low=212.38000099999996, Close=214.009998, Volume=123432400, Adj Close=27.727039)

In [7]:
df.filter('Close>500').show()

+-------------------+------------------+------------------+------------------+------------------+---------+-----------------+
|               Date|              Open|              High|               Low|             Close|   Volume|        Adj Close|
+-------------------+------------------+------------------+------------------+------------------+---------+-----------------+
|2012-02-13 00:00:00|        499.529991|503.83000899999996|497.08998899999995|502.60002099999997|129304000|        65.116633|
|2012-02-14 00:00:00|        504.659988|         509.56002|        502.000008|        509.459991|115099600|        66.005408|
|2012-02-16 00:00:00|        491.500008|        504.890007|         486.62999|502.20999900000004|236138000|        65.066102|
|2012-02-17 00:00:00|        503.109993|507.77002000000005|        500.299995|         502.12001|133951300|        65.054443|
|2012-02-21 00:00:00|506.88001299999996|        514.850021|504.12000300000005|        514.850021|151398800|        66.703738|
|2012-02-22 00:00:00|        513.079994|        515.489983|509.07002300000005|        513.039993|120825600|66.46923100000001|
|2012-02-23 00:00:00|        515.079987|        517.830009|        509.499992| 516.3899769999999|142006900|        66.903253|
|2012-02-24 00:00:00| 519.6699980000001|        522.899979| 518.6400150000001| 522.4099809999999|103768000|        67.683203|
|2012-02-27 00:00:00|        521.309982|             528.5| 516.2800139999999|        525.760017|136895500|        68.117232|
|2012-02-28 00:00:00|        527.960014|        535.410011|        525.850006|        535.410011|150096800|69.36748100000001|
|2012-02-29 00:00:00| 541.5600049999999| 547.6100230000001|        535.700005|        542.440025|238002800|        70.278286|
|2012-03-01 00:00:00|        548.169983|        548.209984| 538.7699809999999| 544.4699780000001|170817500|        70.541286|
|2012-03-02 00:00:00|        544.240013|        546.800018|        542.519974|        545.180008|107928100|        70.633277|
|2012-03-05 00:00:00|        545.420013|         547.47998|        526.000023| 533.1600269999999|202281100|        69.075974|
|2012-03-06 00:00:00|        523.659996|        533.690025| 516.2199860000001|        530.259987|202559700|68.70024599999999|
|2012-03-07 00:00:00| 536.8000030000001|        537.779999|        523.299988| 530.6900099999999|199630200|68.75595899999999|
|2012-03-08 00:00:00| 534.6899950000001|        542.989998|        532.120003|        541.989975|129114300|        70.219978|
|2012-03-09 00:00:00|        544.209999|        547.740013|        543.110001|        545.170021|104729800|70.63198299999999|
|2012-03-12 00:00:00| 548.9799879999999|        551.999977|        547.000023|        551.999977|101820600|        71.516869|
|2012-03-13 00:00:00|        557.540024|            568.18|        555.750023|        568.099998|172713800|73.60278100000001|
+-------------------+------------------+------------------+------------------+------------------+---------+-----------------+
only showing top 20 rows

In [8]:
df.filter('Close>500').select(['Open', 'Close']).show()

+------------------+------------------+
|              Open|             Close|
+------------------+------------------+
|        499.529991|502.60002099999997|
|        504.659988|        509.459991|
|        491.500008|502.20999900000004|
|        503.109993|         502.12001|
|506.88001299999996|        514.850021|
|        513.079994|        513.039993|
|        515.079987| 516.3899769999999|
| 519.6699980000001| 522.4099809999999|
|        521.309982|        525.760017|
|        527.960014|        535.410011|
| 541.5600049999999|        542.440025|
|        548.169983| 544.4699780000001|
|        544.240013|        545.180008|
|        545.420013| 533.1600269999999|
|        523.659996|        530.259987|
| 536.8000030000001| 530.6900099999999|
| 534.6899950000001|        541.989975|
|        544.209999|        545.170021|
| 548.9799879999999|        551.999977|
|        557.540024|        568.099998|
+------------------+------------------+
only showing top 20 rows

In [9]:
df.filter(df['Close']>500).select(['Open', 'Close', 'Volume']).show()

+------------------+------------------+---------+
|              Open|             Close|   Volume|
+------------------+------------------+---------+
|        499.529991|502.60002099999997|129304000|
|        504.659988|        509.459991|115099600|
|        491.500008|502.20999900000004|236138000|
|        503.109993|         502.12001|133951300|
|506.88001299999996|        514.850021|151398800|
|        513.079994|        513.039993|120825600|
|        515.079987| 516.3899769999999|142006900|
| 519.6699980000001| 522.4099809999999|103768000|
|        521.309982|        525.760017|136895500|
|        527.960014|        535.410011|150096800|
| 541.5600049999999|        542.440025|238002800|
|        548.169983| 544.4699780000001|170817500|
|        544.240013|        545.180008|107928100|
|        545.420013| 533.1600269999999|202281100|
|        523.659996|        530.259987|202559700|
| 536.8000030000001| 530.6900099999999|199630200|
| 534.6899950000001|        541.989975|129114300|
|        544.209999|        545.170021|104729800|
| 548.9799879999999|        551.999977|101820600|
|        557.540024|        568.099998|172713800|
+------------------+------------------+---------+
only showing top 20 rows

In [10]:
df.filter((df['Close']<200) & (df['Open']>200) ).select(['Open', 'Close', 'Volume']).show()

+------------------+----------+---------+
|              Open|     Close|   Volume|
+------------------+----------+---------+
|206.78000600000001|    197.75|220441900|
|        204.930004|199.289995|293375600|
|        201.079996|192.060003|311488100|
+------------------+----------+---------+

In [11]:
df.filter((df['Close']<200) & ~(df['Open']>200) ).select(['Open', 'Close', 'Volume']).show()

+------------------+------------------+---------+
|              Open|             Close|   Volume|
+------------------+------------------+---------+
|192.36999699999998|        194.729998|187469100|
|        195.909998|        195.859997|174585600|
|        195.169994|        199.229994|153832000|
|        196.730003|        192.050003|189413000|
|192.63000300000002|        195.460001|212576700|
|        195.690006|194.11999699999998|119567700|
|        196.419996|196.19000400000002|158221700|
|        195.889997|195.12000700000002| 92590400|
|        194.880001|        198.669994|137586400|
|        199.999998|        197.059998|143773700|
|         92.699997|         93.699997| 75415000|
|         94.730003|             94.25| 62777000|
|         94.129997|         93.860001| 45681000|
|         94.040001|         92.290001| 54749000|
|         92.199997|         91.279999| 54525000|
|         91.510002|         92.199997| 35561000|
|         92.309998| 92.08000200000001| 29726000|
|         92.269997|             92.18| 33514000|
|         92.290001|         91.860001| 35528000|
|         91.849998|         90.910004|100898000|
+------------------+------------------+---------+
only showing top 20 rows

In [12]:
df.filter((df['Low']==197.16)).select(['Open', 'Close', 'Volume']).show()

+------------------+------+---------+
|              Open| Close|   Volume|
+------------------+------+---------+
|206.78000600000001|197.75|220441900|
+------------------+------+---------+

In [13]:
res_col = df.filter((df['Low']==197.16)).select(['Open', 'Close', 'Volume']).collect()
res_col

[Row(Open=206.78000600000001, Close=197.75, Volume=220441900)]

In [14]:
res_col[0]

Row(Open=206.78000600000001, Close=197.75, Volume=220441900)

In [15]:
res_dict = res_col[0].asDict()
res_dict

{'Open': 206.78000600000001, 'Close': 197.75, 'Volume': 220441900}

In [16]:
df.select(['Date','Open','Close']).show()

+-------------------+------------------+------------------+
|               Date|              Open|             Close|
+-------------------+------------------+------------------+
|2010-01-04 00:00:00|        213.429998|        214.009998|
|2010-01-05 00:00:00|        214.599998|        214.379993|
|2010-01-06 00:00:00|        214.379993|        210.969995|
|2010-01-07 00:00:00|            211.75|            210.58|
|2010-01-08 00:00:00|        210.299994|211.98000499999998|
|2010-01-11 00:00:00|212.79999700000002|210.11000299999998|
|2010-01-12 00:00:00|209.18999499999998|        207.720001|
|2010-01-13 00:00:00|        207.870005|        210.650002|
|2010-01-14 00:00:00|210.11000299999998|            209.43|
|2010-01-15 00:00:00|210.92999500000002|            205.93|
|2010-01-19 00:00:00|        208.330002|        215.039995|
|2010-01-20 00:00:00|        214.910006|            211.73|
|2010-01-21 00:00:00|        212.079994|        208.069996|
|2010-01-22 00:00:00|206.78000600000001|            197.75|
|2010-01-25 00:00:00|202.51000200000001|        203.070002|
|2010-01-26 00:00:00|205.95000100000001|        205.940001|
|2010-01-27 00:00:00|        206.849995|        207.880005|
|2010-01-28 00:00:00|        204.930004|        199.289995|
|2010-01-29 00:00:00|        201.079996|        192.060003|
|2010-02-01 00:00:00|192.36999699999998|        194.729998|
+-------------------+------------------+------------------+
only showing top 20 rows